version: "3.8"

volumes:
  php-fpm-socket:
  db:
  logs:

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    env_file:
      - ./.env
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
      - logs:/var/log/mysql/mysqld.log
      - ./docker/mysql/mysql.sock:/var/lib/mysql/mysql.sock
    ports:
      - 3306:3306

  app:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./:/work/public/
      - ./docker/mysql/mysql.sock:/var/lib/mysql/mysql.sock
    depends_on:
      - db
    links:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    env_file:
      - ./.env
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./:/work/public/
    ports:
      - 3080:80

  nodejs:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    volumes:
      - ./:/work/public/
    links:
      - nginx
