version: "3.8"

services:
  db:
    container_name: db
    env_file: .env
    build: docker/mysql
    volumes:
      - ./docker/mysql/logs/mysqld.log:/var/log/mysql/mysqld.log
      - ./docker/mysql/logs/mysql-error.log:/var/log/mysql/mysql-error.log
      - ./docker/mysql/db:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  laravel:
    container_name: laravel
    env_file: .env
    build: ./docker/laravel
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    expose:
      - 9000

  nginx:
    container_name: nginx
    env_file: .env
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/logs:/var/www/log
      - .:/var/www/html
    ports:
      - 3080:80
    depends_on:
      - laravel
      - db
      - nodejs

  nodejs:
    container_name: nodejs
    build: ./docker/nodejs
    volumes:
      - .:/var/www/html

  redis:
    container_name: redis
    build: ./docker/redis
    ports:
      - 6379:6379
