version: "3.8"

services:
  db:
    container_name: db
    env_file: .env
    build: docker/mysql
    volumes:
      - ./docker/mysql/logs/mysqld.log:/var/log/mysql/mysqld.log
      - ./docker/mysql/logs/mysql-error.log:/var/log/mysql/mysql-error.log
      - ./docker/mysql/db:/var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060

  laravel:
    container_name: laravel
    env_file: .env
    build: ./docker/laravel
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    ports:
      - 8000:8000
      - 9000:9000

  nginx:
    container_name: nginx
    env_file: .env
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/logs:/var/www/log
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 3080:80
    depends_on:
      - nodejs
      - redis

  nodejs:
    container_name: nodejs
    build: ./docker/nodejs
    volumes:
      - .:/var/www/html

  redis:
    container_name: redis
    build: ./docker/redis
    volumes:
      - ./docker/redis/redis:/etc/redis
    ports:
      - 6379:6379
