version: "3.8"

volumes:
  mysql-data:
  php-fpm-socket:

services:
  db:
    container_name: db
    env_file: ./.env
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./docker/mysql/tmp/logs:/var/log/mysql/mysqld.log
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  laravel:
    container_name: laravel
    env_file: ./.env
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      TZ: 'Asia/Tokyo'
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./:/var/www/html
    depends_on:
      - db
    links:
      - db

  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    volumes:
      - ./:/var/www/html

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./:/work/public
    ports:
      - 3080:80

