version: "3"

volumes:
  php-fpm-socket:
  db-store:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../:/work
    environment:
      - DB_HOST_C=${DB_HOST_C}
      - DB_DATABASE_C=${DB_NAME_C}
      - DB_USERNAME_C=${DB_USER_C}
      - DB_PASSWORD_C=${DB_PASS_C}
      - APP_NAME_C=${APP_NAME_C}
      - APP_ENV_C=${APP_ENV_C}
      - APP_KEY_C=${APP_KEY_C}
      - APP_DEBUG_C=${APP_DEBUG_C}
      - APP_URL_C=${APP_URL_C}
      - WEB_PORT_C=${WEB_PORT_C}
      - MAIL_HOST_C=${MAIL_HOST_C}
      - MAIL_PORT_C=${MAIL_PORT_C}
      - MAIL_USERNAME_C=${MAIL_USERNAME_C}
      - MAIL_PASSWORD_C=${MAIL_PASSWORD_C}
      - MAIL_ENCRYPTION_C=${MAIL_ENCRYPTION_C}
      - MAIL_FROM_ADDRESS_C=${MAIL_FROM_ADDRESS_C}
      - PUSHER_APP_ID_C=${PUSHER_APP_ID_C}
      - PUSHER_APP_KEY_C=${PUSHER_APP_KEY_C}
      - PUSHER_APP_SECRET_C=${PUSHER_APP_SECRET_C}
      - PUSHER_APP_CLUSTER_C=${PUSHER_APP_CLUSTER_C}
      - RECAPTCHA_SITE_KEY_C=${RECAPTCHA_SITE_KEY_C}
      - RECAPTCHA_SECRET_KEY_C=${RECAPTCHA_SECRET_KEY_C}
      - ADMIN_HTTPS_C=${ADMIN_HTTPS_C}

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT_C:-80}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../:/work
    env_file:
      - ../.env
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT_C}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME_C}
      - MYSQL_USER=${DB_USER_C}
      - MYSQL_PASSWORD=${DB_PASS_C}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS_C}
